### ISSUE TITLE
[Request] Publish jadex-distribution-server

### ISSUE THREAD

**Issue by jellelicht** [actoron/jadex#11]
As the title states, please consider publishing a `jadex-distribution-server` artifact to Maven Central for future releases.
Thank you for your consideration.

**Comment by kj-actoron** [comment]
Hi. Thank you for your suggestion, however, we tried to reduce the number of "distribution"-metapackages and as a result dropped support for jadex-distribution-server.
In general, we recommend either using jadex-distribution-standard, for users who do not wish to deal with customizing Jadex for their purposes or, alternatively, basing their projects on jadex-distribution-minimal and adding additional modules as required, such as jadex-kernel-bdiv3 in their project's build system. This allows users to exactly customize Jadex as needed.

If you need a jadex-distribution-server distribution, please let us know how/why this would be helpful to you and we will take it under consideration.

**Comment by jellelicht** [comment]
Thanks for taking the time to address my request; the reasons you give make sense, and the suggestion to mix and match the modules in my local build system is quite easy to do.
