### ISSUE TITLE
How to use Maintain Goals without getting BodyAborted

### ISSUE THREAD

**Issue by jellelicht** [actoron/jadex#12]
I have a belief that consists of a simple queue of items, where I basically want to maintain a goal as long as there are items in this queue.

This leads me to believe that setting both `GoalTargetCondition` and `GoalMaintainCondition` to be implemented as `queue.size() == 0` should do what I want.

This works well in the sense that plans are being deliberated and started as soon as anything is put in my queue, but the issue is what happens when I am in the (for now) last round of executing a plan; the moment (or very soon after) I empty out my queue of the last item, the plan that did this gets stopped. Any statements after the line of code where I empty the queue (`queue.poll()`) seems to not be executed, among which adapting some other beliefs or some logging.

How can I make sure my plan still finishes? I can hack around this by creating a `GoalRecurCondition`-annotated goal and playing around with `orsuccess`, `retrydelay`, `recur`, but the semantics of a Maintain Goal seem like a much better fit;

**Comment by jellelicht** [comment]
Some clarification; this is only a problem if in the plan for handling my Maintain Goal, I dispatch to a sub-goal; it seems that my plan never resumes after that. That also makes sense, as the ‘target’ has been met; is there some way in which I can enforce that my plan will be resumed?

**Comment by lb-actoron** [comment]
Plan abort on goal success is intended behavior. Reason is that plan and goal semantics is separated meaning that an agent tries to fulfill a goal and once it has been achieved there is no reason to continue plan execution. You can defer goal achievement e.g. be removing the element from the queue only at plan end. We also had startAtomic() endAtomic() before bdiv3 to create atomic blocks but did not need it in newer versions any more.
