### ISSUE TITLE
Way to set custom ClassLoader

### ISSUE THREAD

**Issue by jellelicht** [actoron/jadex#4]
Jadex 3.0 used to support setting your own classloaders, or it seems that [this javadoc](https://download.actoron.com/docs/releases/latest/javadoc/jadex/base/Starter.html#createPlatform-jadex.base.PlatformConfiguration-java.lang.ClassLoader-) seems to indicate so. 

How do I do the same thing in jadex 4.0?

**Comment by kj-actoron** [comment]
Hi. For Jadex 4.0, we've simplified the platform configuration a bit. Unfortunately this means that more advanced configurations options, such as setting the classloader, are a bit more difficult to get to. Here is an example how to start a platform with a custom classloader:

```java
Classloader cl = ...;
IPlatformConfiguration config = jadex.base.PlatformConfigurationHandler.getPlatformConfiguration(cl);
Starter.createPlatform(config);
```

**Comment by jellelicht** [comment]
It seems that the proposed snippet helps to find certain classes, but does not allow one to create components on the fly:

I get, when passing as `ClassLoader cl = MyClass.getClassLoader();`:
```
Execution error (ServiceNotFoundException) at jadex.bridge.service.types.cms.SComponentManagementService$3/exceptionOccurred (SComponentManagementService.java:553).
No component factory found for: MyClass.class
```

This only works if I _also_ have MyClass.class available in the `jdk.internal.loader.ClassLoaders$AppClassLoader`, after which I can use one of many JVM tricks to overwrite that specific class with the definition I actually want in a different ClassLoader which I pass to my IPlatformConfiguration.

Is there some way in which component factories will also be looked for in the `cl` I pass to my IPlatformConfiguration?

**Comment by jellelicht** [comment]
@kj-actoron Would there be some way I can disable lookups for component factories in the AppClassLoader, or force these to go through my configured classloader?

**Comment by kj-actoron** [comment]
It is certainly possible to hard-load factories without the so-called multi-factory (effectively a meta-factory that dynamically loads additional factories as needed). See e.g. in jadex.base.PlatformConfigurationHandler.getMinimal() for an example of a microagent-only configuration.

It still eludes me, what precisely is going wrong in your case.

**Comment by jellelicht** [comment]
I’m trying to work with generated classes; that is, they are loaded in the JVM, but there are no on-disk .class files; only the in-memory bytes :) 

EDIT: and there is a ClassLoader, naturally :)
