### ISSUE TITLE
How to define Agents without nullary constructor

### ISSUE THREAD

**Issue by jellelicht** [actoron/jadex#6]
Because of library constraints, my `@Agent`-annotated class `MyAgent` cannot have a nullary constructor. 

Would it be possible to introduce a way to register a factory method (e.g. as a `Supplier<MyAgent>`, perhaps with a mapping from `MyAgent.class` to this factory object)

**Comment by jellelicht** [comment]
I've now found that sticking a `"__pojo"`-entry in the args in `new CreationInfo(args)` _seems_ to be doing the trick.

**Comment by lb-actoron** [comment]
One could e.g. add a special annotation for a static method in the agent that then has to create the pojo such as that:

@AgentPojoCreation
public MyAgent createAgent()
{
.... 
return myagent; 
} 

Would this be helpful?

**Comment by lb-actoron** [comment]
And yes, in CreationInfo you can set the pojo via:
public CreationInfo setPojo(Object pojo)

**Comment by lb-actoron** [comment]
The pojo in creation info can be string, class or an object. It is evaluated in the prepare method of PlatformComponent as follows
(so it uses the __pojo trick you mentioned):

public CreationInfo prepare(CreationInfo info)
	{
		if(info==null)
			info = new CreationInfo();
//		if(info.getParent()==null)
//			info.setParent(getId());
		
		Object component = info.getPojo();
		String modelname = null;
		
		if(component instanceof String)
		{
			modelname = (String)component;
			info.setFilename(modelname);
		}
		else if(component instanceof Class<?>)
		{
			modelname = ((Class<?>)component).getName()+".class";
			info.setFilename(modelname);
		}
		else if(component != null)
		{
			modelname = component.getClass().getName()+".class";
			info.addArgument("__pojo", component); // hack?! use constant
			info.setFilename(modelname);
		}
		
		return info;
	}

**Comment by jellelicht** [comment]
`@AgentPojoCreation` would be useful, but knowing that the pojo-trick won't suddenly break everything later on is enough for me to now. Thanks!
